name: Node.js CI

on:
  push:
    branches: ["deploy-to-google"]
  pull_request:
    branches: ["deploy-to-google"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: nodecluser1 
  GKE_ZONE: asia-south1 
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/microservices-gateway:latest
    

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test Book Service
        working-directory: ./Books
        run: |
          npm install
          npm test

      - name: Test User Service
        working-directory: ./User
        run: |
          npm install
          npm test

      - name: Test Order Service
        working-directory: ./Orders
        run: |
          npm install
          npm test

  SnykSecurityScan:
    needs: buildAndTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Scan
        run: snyk test --json > snyk_report.json || true

      - name: Upload Snyk report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk_report.json

  SecretsScan:
    needs: SnykSecurityScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

  dockerize:
    needs: SecretsScan
    name: Dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: docker build books
        run: |
          docker build ./Books -t pasanchamikara99/books
      - name: docker build orders
        run: |
          docker build ./Orders -t pasanchamikara99/orders
      - name: docker build books
        run: |
          docker build ./User -t pasanchamikara99/user
      - name: docker build gateway
        run: |
          docker build ./gateway -t pasanchamikara99/gateway
      - name: docker images push
        run: |
          docker push pasanchamikara99/books
          docker push pasanchamikara99/orders
          docker push pasanchamikara99/user
          docker push pasanchamikara99/gateway

  deploy:
    needs: dockerize
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag $IMAGE gateway/Dockerfile .

      - name: Install kubectl
        run: gcloud components install kubectl

      - name: Install GKE gcloud Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          echo "PATH=$PATH:/opt/hostedtoolcache/gcloud/472.0.0/x64/bin" >> $GITHUB_ENV

      - name: Set up Kubectl
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl apply -f kubernetes/k8s.yaml --validate=false
          kubectl rollout status deployment/web-app-deployment

      - name: Verify deployment
        run: kubectl get all
